DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON usuario
FOR EACH ROW
BEGIN
DELETE FROM usuario_cancoes
WHERE OLD.ID = USUARIO_ID;
DELETE FROM usuario_artista WHERE OLD.ID = USUARIO_ID;
END $$
DELIMITER ;
